# Chapter 10 - ANOVA: Comparing several means ====

# Initializing ====
library(car)
library(compute.es) #' `mes()`
library(dplyr)
library(ggplot2)
library(magrittr)
library(multcomp) #' `glht()`
library(pastecs)
library(psych)
library(WRS2) #' robust tests

libido <- c(3,2,1,1,4,5,2,4,2,3,7,4,5,3,6)
dose <- gl(3,5, labels = c("Placebo", "Low Dose", "High Dose"))
df <- data.frame(dose, libido)

# Creating error bar to explore possible trends ====
df %>% 
  
  # Criando primeira camada
  ggplot(aes(x = dose, y = libido, shape = dose)) +
  
  geom_point(position = 'jitter') +
  
  # Criando o intervalo de confiança
  stat_summary(fun.data = mean_sdl,
               fun.args = list(mult = 1),
               colour = 'steelblue',
               geom = 'errorbar',
               width = .1) +
  
  # Criando o ponto de média
  stat_summary(fun.data = mean_sdl,
               fun.args = list(mult = 1),
               colour = 'steelblue',
               geom = 'point') +
  
  # Criando a linha que conecta
  stat_summary(fun = mean,
               geom = 'line',
               aes(x = as.numeric(dose), y = libido),
               colour = 'steelblue') +
  
  # Colocando tema
  theme_minimal()

# Looking at descriptive statistics for each group ====
by(df$libido, df$dose, stat.desc, basic = F, norm = T)

# Assessing homogeneity of variance between groups ====
leveneTest(df$libido, df$dose, center = 'median')

#' The test is non-significant, pointing to homogeneity of variance.

# Conduction an one-way ANOVA ====
#' `lm()` could be used to conduct the analysis
lm <- lm(libido ~ dose, data = df)
summary(lm)

#' However, `lm()` doesn't show specific traditional ANOVA outputs
#' Those are shown in `aov()`, a wrapper on the `lm()` function
aov_output <- aov(libido ~ dose, data = df)
summary(aov_output)

#' Notice that the same p-value is reported in both functions (0.0247).
#' Now let's look at the interesting plot generated by `aov()`
plot(aov_output)

# Conduction an one-way ANOVA when variances are not equal ====
#' When variances differ, we can use *Welch's F*
oneway_output <- oneway.test(libido ~ dose, data = df)
oneway_output

#' It's worth noting that the degrees of freedom for the Sum of Squared Residuals
#' is now 7.9, a relevant difference from the 12 dfs of before.

# Conducting a robust ANOVA ====
t1way_output <- t1way(libido ~ dose, data = df, tr = .1)
t1way_output

# We could also compare medians
med1way_output <- med1way(libido ~ dose, data = df)
med1way_output

# Conducting a robust ANOVA with bootstrap ====
t1waybt_output <- t1waybt(libido ~ dose, data = df, nboot = 2000)
t1waybt_output

# Planning contrasts (High > Low > Placebo) ====
#' Having already planned the weights, you just insert it into the function
contrast1 <- c(-2, 1, 1)
contrast2 <- c(0, -1, 1)

contrasts(df$dose) # before

contrasts(df$dose) <- cbind(contrast1, contrast2)

contrasts(df$dose) # after

#' Running `aov()` again
aov_contrast_output <- aov(libido ~ dose, data = df)
summary.lm(aov_contrast_output)

#' Having already planned the comparisons in advance, we know that there's
#' a significant difference between the means of placebo and viagra groups,
#' which is denoted by dosecontrast1's p < 0.05. Also, there isn't a significant
#' difference between the means of High Dose Viagra group and Low Dose Viagra 
#' group, shown by dosecontrast2's p > 0.05.

#' However, since our hypothesis pointed towards High > Low > Placebo, all
#' p-values can be divided by 2, since we already specified this one-tailed
#' hypothesis. Thus, dosecontrast1's p = 0.0146 and dosecontrast2's p = 0.0326.
#' We could now reject the null hypothesis (but only because the directional
#' relationship had already been stablished in the beggining).

# Contrasts with trend analysis ====
contrasts(df$dose) # before

contrasts(df$dose) <- contr.poly(3)

contrasts(df$dose) # after

#' Running `aov()` again
aov_output <- aov(libido ~ dose, data = df)
summary.lm(aov_output)

#' *dose.L* tests if the relationship is linear, while *dose.Q* tests if the
#' relationship is quadratic (starts going up and then comes down). We could
#' be confident that as the viagra doses get bigger, libido tends to go up,
#' t = 3.16 and p = 0.008. Also, we don't have evidences to think that we're
#' observing a quadratic trend, since t = 0.52 and p > 0.612.

# Post hoc tests - Bonferroni and Benjamini-Hochberg ====
#' *Bonferroni* - controls for Type I error rate, conservative
bonferroni_output <- pairwise.t.test(df$libido, df$dose,
                                     p.adjust.method = 'bonferroni')

bonferroni_output

#' *Benjamini-Hochberg* - controls for False Discovery Rate, liberal
bh_output <- pairwise.t.test(df$libido, df$dose,
                             p.adjust.method = 'BH')

bh_output

#' Both post hocs show that High Dose is significantly different from Placebo,
#' and that low dose isn't significantly different from placebo or high dose.

# Post hoc tests - Tukey and Dunnett ====
#' *Tukey* - controls for Type I error rate, conservative
tukey_output <- glht(aov_output, linfct = mcp(dose = "Tukey"))
summary(tukey_output)
confint(tukey_output)

#'  'You can replace “method” in the command above with “Dunnett”, “Tukey”, 
#'  “Sequen”, “AVE”, “Changepoint”, “Williams”, “Marcus”, “McDermott”, 
#'  “UmbrellaWilliams”, and “GrandMean”'

#' *Dunnett* - compares groups based on a baseline; in this case, placebo (1)
dunnett_output <- glht(aov_output, linfct = mcp(dose = "Dunnett"), base = 1)
summary(dunnett_output)
confint(dunnett_output)

# Robust post hoc tests ====
#' `lincon()` with trimmed means, baseline 20% (tr = .2)
lincon_output <- lincon(libido ~ dose, data = df)
lincon_output

#' `mcppb20()` with percentile bootstrap & trimmed means
mcppb20_output <- mcppb20(libido ~ dose, data = df, nboot = 2000)
mcppb20_output

# Calculating ANOVA's effect size ====
#' Remember that *R² = SSm/SSt* - percentage of explanation from the total
#' variation provided by the model, simple as that
#' `aov()`'s output provides both values, so we can calculate that
aov_output

r_squared <- 20.13333/(23.6 + 20.13333)
r <- sqrt(r_squared)
r

#' That isn't necessary though, 'cause it's already provided by the function
summary.lm(aov_output)

#' *Multiple R-squared:  0.4604*
#' Since r > 0.5, the effect is considered to be large
#' R squared is called *eta-squared* (η²) in the context of ANOVA
#' So, η² = 0.46

#' Omega squared is a measure of effect size that controls for the assumption
#' that we're trying to estimate this effect size *in the population*.
#' *ω² = (SSm - (dfm)MSr) / SSt + MSr)*
#' Omega can be understood as an unbiased estimate of r
#' Again, we can calculate omega following `aov()`'s output
aov_output

omega_squared <- (20.13333 - 2 * (23.6/12))/ ((20.13333 + 23.6) + (23.6/12))
omega_squared

omega <- sqrt(omega_squared)
omega

#' About omega: 'it has been suggested that values of .01, .06 and .14 represent 
#' small, medium and large effects respectively (Kirk, 1996).'

# Calculating the effect sizes for the difference between pairs of groups ====
#' The `mes()` function calculates the effect sizes of these differences
#' We only need to follow its formula, which is:
#' `mes(MEAN_group1, MEAN_group2, SD_group1, SD_group2, N_group1, N_group2)`
#' Having said that, we could use `psych::describe()` and input those values
by(df$libido, df$dose, describe)

# Placebo vs. Low Dose
mes_placebo_low <- mes(2.2, 3.2, 1.3, 1.3, 5, 5)
mes_placebo_low$d # mean difference
mes_placebo_low$r # correlation coefficient

# Placebo vs. High Dose
mes_placebo_high <- mes(2.2, 5, 1.3, 1.58, 5, 5)
mes_placebo_high$d # mean difference
mes_placebo_high$r # correlation coefficient

# Low Dose vs. High Dose
mes_low_high <- mes(3.2, 5, 1.3, 1.58, 5, 5)
mes_low_high$d # mean difference
mes_low_high$r # correlation coefficient

# Calculating r after planned contrasts ====
#' Another way to do that is to follow another r formula:
#' *R = SQRT [ t² / (t² + df)]*
rcontrast <- function(t, df) {
  
  r <- sqrt(t^2 / (t ^ 2 + df))
  
  print(paste("r = ", r))
  
}

#' To assess the t and df values, we execute the `aov()` contrast output again
summary.lm(aov_output)

rcontrast(2.474, 12)
rcontrast(2.029, 12)

#' Both effects could be considered large since r > 0.5

# Reporting ANOVA ====

#' *General form*
#' "There was a significant effect of Viagra on levels of libido, F(2, 12) = 
#' 5.12, p < .05, ω = .60."

#' If the *linear contrast* is done, this could also be reported:
#' "There was a significant linear trend, F(1, 12) = 9.97, p < .01, ω = .62, 
#' indicating that as the dose of Viagra increased, libido increased 
#' proportionately"

#' *Planned contrasts*
#' "Planned contrasts revealed that taking any dose of Viagra significantly 
#' increased libido compared to having a placebo, t(12) = 2.47, p < .05 
#' (one-tailed), and that taking a high dose significantly increased libido 
#' compared to taking a low dose, t(12) = 2.03, p < .05 (one-tailed)."

#' *Bonferroni and effect sizes*
#' "Despite fairly large effect sizes, Bonferroni tests revealed non-significant 
#' differences between the low-dose group and both the placebo, p = .845, 
#' d = -0.77, and highdose, p = .196, d = -1.24, groups. The high-dose group, 
#' however, had a mean almost 2 standard deviations bigger than the placebo 
#' group, p = .025, d = -1.93."

